### ISSUE TITLE
[inertia-vue] The `useForm` helper returns `any` type

### ISSUE THREAD

**Issue by valh1996** [laravel/precognition#79] opened 2024-06-30 20:00 UTC
### Laravel Precognition Plugin Version

0.5.5

### Laravel Version

0.5.5

### Plugin

Vue w/ Inertia

### Description

The `useForm` helper returns `any` type, which is annoying because I have no idea what methods are available. 
Is this intentional?

In addition, if I use the `transform()` method, data isn't typed and so the properties of my form aren't found.

### Steps To Reproduce

Simply import `useForm` from the Inertia plugin and you'll see that it is not typed:
```ts
import { useForm } from 'laravel-precognition-vue-inertia';
```

I see that `laravel-precognition-vue` does have a return type, unlike `laravel-precognition-view-inertia`: https://github.com/laravel/precognition/blob/main/packages/vue-inertia/src/index.ts#L8

**Comment by crynobone** [comment] 2024-07-01 05:22
Hi there, if you could whip up a PR for us to look at, that'd be great! Thanks.

Duplicate of #63 and previous fail attempt: #64

**Closed by crynobone** 2024-07-01 05:22 UTC

**Comment by valh1996** [comment] 2024-07-01 07:46
Hi @crynobone, I've just looked at the PR list, it seems to be more linked to #77.
I'll wait for @timacdonald review then, thanks.
