### ISSUE TITLE
form.submit() triggers a CanceledError from Axios

### ISSUE THREAD

**Issue by hackel** [laravel/precognition#74] opened 2024-06-14 15:24 UTC
### Laravel Precognition Plugin Version

0.5.5

### Laravel Version

10.48.10

### Plugin

Vue

### Description

I've got a pretty basic form using Precognition, and all the form validation works great.  Using Firefox, when I call `form.submit()` to make a POST request, I get an Axios ERR_CANCELED error, and it never tries to contact the server.  The really weird thing is that if I double-click the submit button, the request goes through fine on the second click, like there's some kind of race condition.  This *usually* doesn't happen if I'm submitting a PUT request, but sometimes it does, and I haven't been able to identify a pattern.  This error happens on my colleague's machine as well.  If I test in Chromium, however, it works fine.

I realize this might not be a Precognition bug, but when I make the same POST submission by calling axios directly, it works just fine.

### Steps To Reproduce

Here's a simplified example of what I'm doing.
```js
const form = useForm(
    () => (props.terminal.id === 0 ? 'post' : 'put'),
    () => (props.terminal.id === 0 ? '/api/terminals' : `/api/terminals/${props.terminal.id}`),
    {
        name: props.terminal.name ?? '',
        type: props.terminal.type ?? '',
        phone: props.terminal.phone ?? '',
        // ...etc.
    },
);
```
```js
const onSubmit = async () => {
    try {
        const response = await form.submit();
        const terminal = response.data;
        emit('saved', terminal);
    } catch (error) {
        console.error(error);
    }
};
```

**Comment by timacdonald** [comment] 2024-06-17 07:05
Sounds like this might be a duplicate of https://github.com/laravel/precognition/issues/73

We should have a fix out for this shortly. Let's follow along in the other issue to keep things together.

**Closed by timacdonald** 2024-06-17 07:05 UTC

**Comment by timacdonald** [comment] 2024-06-20 01:47
@hackel, I'm also wondering if you could add the following to see if it makes a change on your end?

```js
let submitting = false

const onSubmit = async () => {
    if (submitting) {
        return
    }

    submitting = true

    try {
        const response = await form.submit();
        const terminal = response.data;
        emit('saved', terminal);
    } catch (error) {
        console.error(error);
    } finally {
        submitting = false
    }
};
```

**Comment by hackel** [comment] 2024-06-21 18:28
@timacdonald I'm still seeing this issue even after making those changes.

**Comment by timacdonald** [comment] 2024-06-24 23:17
I've got a fix up that should address this one for you: https://github.com/laravel/precognition/pull/78
